<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>Test Scenario AOS0001</description>
   <name>TS_ASM0001_LOGIN</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>a0c33610-f1dd-4e79-8146-f2e0012c78ab</testSuiteGuid>
   <testCaseLink>
      <guid>2b10a300-274f-4bcc-b19f-e622aba7a0df</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ASM0001/001 - Login With Registered Account</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>ac53f407-61c8-44cb-86cd-20cc48a26576</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>1-1</value>
         </iterationEntity>
         <testDataId>Data Files/AOS0001/DATA_REGISTERED_ACCOUNT</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>ac53f407-61c8-44cb-86cd-20cc48a26576</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>USERNAME</value>
         <variableId>905e050c-8bfe-4f53-9a82-8371a6b9c37e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ac53f407-61c8-44cb-86cd-20cc48a26576</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>PASSWORD</value>
         <variableId>bea69f85-0a18-44d7-8f27-3ecd68475166</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9eca1295-8716-4e15-94e0-3c4521df9422</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ASM0001/002 - Login With Face Recognition Biometric</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>0167eef2-3b24-4586-96ba-d9efc5d02df2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ASM0001/003 - Login With Fingerprint Biometric</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>4597f0d8-49f2-426d-93dd-837a9ca9a495</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ASM0001/004 - Login With Facebook Account</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>3e2294ef-4794-44ac-86b8-61c3c48ddf40</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ASM0001/005 - Login With Unregistered Account</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>c3d46365-bf29-43ea-8a52-6000377557aa</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/AOS0001/DATA_UNREGISTERED_ACCOUNT</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>c3d46365-bf29-43ea-8a52-6000377557aa</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>USERNAME</value>
         <variableId>80e5e9eb-aa47-459d-ade6-1a8355fc108e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>c3d46365-bf29-43ea-8a52-6000377557aa</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>PASSWORD</value>
         <variableId>7b705de5-3a14-4aec-baea-bcaf8e81dd17</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ee4c6c48-1d8e-43be-b274-4b5a77044f6b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <iterationNameVariable>
         <defaultValue>''</defaultValue>
         <description>VARIABLE FOR USERNAME FIELD</description>
         <id>3438e7c1-0208-4591-aeab-e266bae6f5ec</id>
         <masked>false</masked>
         <name>email</name>
      </iterationNameVariable>
      <testCaseId>Test Cases/ASM0001/006 - Login With Registered Email Address</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>159cd877-68b5-4f72-b146-19728ddd9f85</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/AOS0001/DATA_REGISTERED_ACCOUNT</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>159cd877-68b5-4f72-b146-19728ddd9f85</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>EMAIL</value>
         <variableId>3438e7c1-0208-4591-aeab-e266bae6f5ec</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>159cd877-68b5-4f72-b146-19728ddd9f85</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>PASSWORD</value>
         <variableId>1d00bc0b-5baa-4787-ab29-6c992ff0ac16</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e449fbec-66f0-47db-a00d-d9691b6577ff</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ASM0001/007 - Login With Invalid Password 1x</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>0b32139d-bfe7-4243-87dd-12dd1c5a713e</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/AOS0001/DATA_REGISTERED_ACCOUNT</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>0b32139d-bfe7-4243-87dd-12dd1c5a713e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>USERNAME</value>
         <variableId>b5768b96-354b-48e8-abe3-ffea3cb01448</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bf5db06b-04d5-4115-8f3f-9d660440452e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3318199e-ff88-4ffa-8d9a-064eb0fa1b5a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ASM0001/008 - Login With Invalid Password 4x</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>add38d93-f0c6-44ac-a825-3992d0ad21da</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/AOS0001/DATA_REGISTERED_ACCOUNT</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>add38d93-f0c6-44ac-a825-3992d0ad21da</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>USERNAME</value>
         <variableId>4c8522cf-b34b-4ecc-b5da-372de362ebed</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>86a96ed8-235f-4d5a-8c55-31f74bf92125</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c6083ced-504d-45ed-9999-1aaaaeee93dc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ASM0001/009 - Login With Temporarily Blocked Account Status</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>02b2e39b-2bdb-44ed-b783-f55e1456b2af</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>443da21a-3107-443a-9e75-c2f5a5e240a5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>72355fe5-1181-437c-b208-285e9f7f942d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ASM0001/010 - Login Without Input Mandatory Fields</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>1f99e0db-9a17-4353-b857-60d3b0ac2ff9</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/AOS0001/DATA_REGISTERED_ACCOUNT</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>1f99e0db-9a17-4353-b857-60d3b0ac2ff9</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>USERNAME</value>
         <variableId>1ea90146-16a1-444d-bb9b-b3e3799f9ee1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c7969ac2-4895-4a3d-baec-d2a5526439ea</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
