<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>Test Scenario AOS0001</description>
   <name>TS_AOS0001_LOGIN</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>a0c33610-f1dd-4e79-8146-f2e0012c78ab</testSuiteGuid>
   <testCaseLink>
      <guid>02cb136c-4ed3-4ae3-beb1-5f1e2e8fe61e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AOS0001/001 - Verify Login Screen Visible Username, Password Fields and Button Login</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>2b10a300-274f-4bcc-b19f-e622aba7a0df</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AOS0001/002 - Verify Login With Registered Account</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>905e050c-8bfe-4f53-9a82-8371a6b9c37e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bea69f85-0a18-44d7-8f27-3ecd68475166</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4597f0d8-49f2-426d-93dd-837a9ca9a495</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AOS0001/003 - Verify Login With Facebook</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>14d48792-bfb3-456c-8870-75075a7e2c0d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AOS0001/004 - Verify Login With Reset Password</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>3e2294ef-4794-44ac-86b8-61c3c48ddf40</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AOS0001/005 - Verify Login With Unregistered Account</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>80e5e9eb-aa47-459d-ade6-1a8355fc108e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7b705de5-3a14-4aec-baea-bcaf8e81dd17</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ee4c6c48-1d8e-43be-b274-4b5a77044f6b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AOS0001/006 - Verify Login Fill In The Username Field With Registered Email</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3438e7c1-0208-4591-aeab-e266bae6f5ec</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d00bc0b-5baa-4787-ab29-6c992ff0ac16</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e449fbec-66f0-47db-a00d-d9691b6577ff</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AOS0001/007 - Verify Login With Invalid Password 1x</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b5768b96-354b-48e8-abe3-ffea3cb01448</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bf5db06b-04d5-4115-8f3f-9d660440452e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3318199e-ff88-4ffa-8d9a-064eb0fa1b5a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AOS0001/008 - Verify Login With Invalid Password 3x</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4c8522cf-b34b-4ecc-b5da-372de362ebed</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>86a96ed8-235f-4d5a-8c55-31f74bf92125</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>72355fe5-1181-437c-b208-285e9f7f942d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AOS0001/009 - Verify Login Without Fill The Password Field</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>0598252c-d5fb-43cf-8da2-9d38663e7b94</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AOS0001/010 - Verify Login Without Fill The Username And Password Fields</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
